{{- if .Values.externalSecrets.enabled }}
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ include "starter.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "starter.labels" . | nindent 4 }}
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: {{ include "starter.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
  {{- with .Values.externalSecrets.externalSecretsFrom }}
      key: {{- toYaml . | trimPrefix "-" }}
  {{- end }}
{{- end }}