import Head from "next/head";
import styles from "../styles/Home.module.css";

import "@hackerrank/hrds-styles/dist/main.css";
import "react-calendar/dist/Calendar.css";

// @ts-ignore-next-line
import { ActivityIcon } from "ui-icons";
// @ts-ignore-next-line
import { HRButton, HRAvatar } from "@hackerrank/hrds";
import { useState } from "react";
// @ts-ignore-next-line
import { Calendar } from "react-calendar";
import Link from "next/link";

export default function Home() {
	const [value, onChange] = useState(new Date());

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<ActivityIcon />
			<HRButton>Test me</HRButton>
			<HRAvatar></HRAvatar>

			<div
				style={{
					width: "300px",
				}}
				className={styles.calendar_container}
			>
				<Calendar onChange={onChange} value={value} />
			</div>

			<Link href="/dashboard" prefetch={false}>
				Dashboard
			</Link>
		</div>
	);
}
