import "@/styles/globals.css";
import { Open_Sans as OpenSans } from "@next/font/google";
import type { AppProps } from "next/app";
import Head from "next/head";

const openSans = OpenSans({
	weight: ["400", "600"],
	display: "swap",
	subsets: ["latin"],
});

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
				<style jsx global>{`
					html {
						font-family: ${openSans.style.fontFamily};
					}
				`}</style>
			</Head>
			<Component {...pageProps} />
		</>
	);
}
